spring:
  application:
    name: webull-web-auth-feign
server:
  port: 8095
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8091/eureka/
#    enabled: false
feign:
  hystrix:
    enabled: true
#ribbon:
#  eureka:
#    enabled: false
